[settings]
paranoid = true
not_found_auto_install = false
disable_backends = ["asdf"]

[tools]
awscli = "latest"
gemini-cli = "latest"
go = "latest"
jq = "latest"
k9s = "latest"
kind = "latest"
kubectl = "latest"
minikube = "latest"
neovim = "latest"
node = "latest"
python = "latest"
terraform = "latest"
uv = "latest"
helm = "latest"
yq = "latest"
