[settings]
paranoid = true
not_found_auto_install = false
disable_backends = ["asdf"]

[tools]
awscli = "latest"
gemini-cli = "latest"
gh = "latest"
go = "1.24"
jq = "latest"
k9s = "latest"
kind = "latest"
kubectl = "1.33"
minikube = "latest"
neovim = "latest"
node = "22"
python = "3.12"
terraform = "1.11"
uv = "latest"
helm = "latest"
yq = "latest"
